# GoReleaser configuration for PackWiz Wrapper
# Documentation: https://goreleaser.com
#
# Build Matrix:
# - GUI builds: Windows/Linux amd64 only (requires CGO for Fyne, cross-compilation to ARM64 not supported)
# - Headless builds: Windows/Linux amd64/arm64 (no CGO, full cross-compilation support)
# Total: 6 build artifacts

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  # GUI version (Windows and Linux - CGO enabled, amd64 only due to cross-compilation limitations)
  - id: "gui"
    main: "./cmd/pw"
    binary: "pw-gui"
    tags:
      - gui
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - windows
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1

  # Headless version (Windows and Linux only)  
  - id: "headless"
    main: "./cmd/pw"
    binary: "pw-cli"
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: "gui-archives"
    builds:
      - gui
    name_template: "pw-gui_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    
  - id: "headless-archives" 
    builds:
      - headless
    name_template: "pw-headless_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: Merith-TK
    name: packwrap2
  draft: false
  prerelease: auto
  name_template: "PackWiz Wrapper v{{.Version}}"
